### ISSUE TITLE
Create and update promotional tweets document

### ISSUE THREAD

**Issue by prefontaine** [MozillaFoundation/Story-Engine#103]

**Comment by OpenMatt** [comment]
@ankuhl can you paste the link for that here?

**Comment by ankuhl** [comment]
EDIT/New Doc (Spreadsheet) for Tweets @openmatt @prefontaine

https://docs.google.com/a/facilitatingchange.org/spreadsheets/d/1c6eAArxYj7DLQJ4FvrSRqvrcFz58PfWPoI8eFQseOVc/edit?usp=sharing

**Comment by prefontaine** [comment]
@ankuhl I'm wondering if this would be better as a spreadsheet because then we could sort by name, issue, etc. What do you think?

**Comment by OpenMatt** [comment]
can we mark this one closed?
