### ISSUE TITLE
Send email newsletter to MoFo staff

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#104]
building off the google doc w. tweets that alecia started

I have some ideas here, and could help shape the template we use.

e.g., framing as "#internethealth heroes"

**Comment by OpenMatt** [comment]
@ankuhl can you paste the link to the google doc you're using for this?

**Comment by ankuhl** [comment]
https://docs.google.com/a/facilitatingchange.org/document/d/1lH9GezTZB0GVwlxtoemIexyAo1VEBQ29GxeJNwl5FF4/edit?usp=sharing

**Comment by OpenMatt** [comment]
@ankuhl I've started editing but need to wrap for the day. Will have my edit finished morning of Tues, April 11.

**Comment by OpenMatt** [comment]
Hey, guys. I took a pass at tweaking the template for the newsletter:
https://docs.google.com/document/d/1lH9GezTZB0GVwlxtoemIexyAo1VEBQ29GxeJNwl5FF4/edit#

Ticket: https://huboard.com/MozillaFoundation/Story-Engine/#/issues/217898231

Main things for me were:
1) polish 2 or 3 #openinnovation stories. I tried to turn our raw transcripts into slightly more polished pieces for 2 or 3 highlight stories. I think it's important to reward the click with something easier to read. 
2) lead with tweets. As a way to provide a dead simple summary and encourage staff to share. 
3) bump up the "network members in the news" section. I think that's a great element. 

Overall: I really like leveraging this as a way to make our network members the "heroes" of our work. Including: helping them get love and more attention on Twitter, etc. 

In general, we still need to get better at pulling quotes that are pithy and short. But we can always hone as we go -- I think it's looking pretty good for version 1.0. See what you think.

**Comment by ankuhl** [comment]
Sounds good! Thank you for taking the time to look at this and give me pointers on how to improve the content!

**Comment by prefontaine** [comment]
Thanks so much, Matt. I'll take a look and forward on to Chris by tomorrow.

//////////////////////////////////////
Christine Prefontaine
Founder, FacilitatingChange.org
Co-Creator, StoryEngine.io
Book a time with me » <https://calendly.com/christine-prefontaine>
Signal: +1 202 499 8554
Wire: @prefontaine
