### ISSUE TITLE
Add / synch Science hub stories 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#11]
@acabunoc has a spreadsheet full of impact stories she's been collecting. Let's add them or make a plan for how we want to work together going forward.

**Comment by prefontaine** [comment]
@OpenMatt Agreed. Can you connect us? Also Meghan mentioned that there was someone -- Lotta? Maybe I mis-heard -- working with Mozilla internal comms who was interviewing folks with same 5 questions and that I should look at her findings.

**Comment by OpenMatt** [comment]
1) re: Lotta's internal comms work. I disagree -- her interviews are exclusively _MoFo staff._ So I don't think that data is interesting for us. 

2) re: Science stories. I'd say we already have an early abundance of science stories from the network survey. Let's punt on this ticket for now and come back to it in October. I think by then we'll have more fleshed out on the site that will help us show vs. tell the value of the work, which will make it easier for staff to see / understand what we're up to. 

I'll move this to the Oct heartbeat so we can come back to it then.

**Comment by abbycabs** [comment]
My spreadsheet is mostly keeping track of my communications with community members, when we've interviewed them, when we've followed up -- very CRM-like.

We can connect in October @prefontaine :)
