### ISSUE TITLE
Improve hierarchy between Question and Answer text.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Story-Engine#129]
This chunk of text contains two question and answers, but when scanning the page, it's hard to tell them apart...

![image](https://user-images.githubusercontent.com/25212/27155313-55a0ad92-510d-11e7-855d-135beac55a4a.png)

From https://storyengine.io/stories/web-literacy/ani-martinez/

Here's the same section with a couple of small changes...

![image](https://user-images.githubusercontent.com/25212/27155395-af11980a-510d-11e7-9289-b83b99ec1497.png)

I've added the following CSS to make this happen...

```
.entry-content h3 {
  font-weight: bold;
  color: #333;
}
```

I think it looks better and is easier to scan.

**Comment by flukeout** [comment]
Okay cool, looks like I got access to the Wordpress, so I'll look into this in the next couple of days.

**Comment by prefontaine** [comment]
Great. One of the reasons I left H3 lighter was to distinguish between H2
and H3.

**Comment by flukeout** [comment]
Okay, I've made the following changes:

* Made the ``h3`` headings bold.
* Increased the margin above the ``h3`` when it is right after an ``h2`` element.
  * This helps the hierarchy between those two headings.
* Kept the font color of the ``h3`` the same as before, as making it darker conflicted with the ``h2`` right above it.

Check it out here - https://storyengine.io/stories/web-literacy/ani-martinez/

**Comment by flukeout** [comment]
For some reason the changes are reflected in Firefox but not in Chrome, investigating. Weird. Should appear as...

![image](https://user-images.githubusercontent.com/25212/27239035-28c3851a-5284-11e7-90c8-e838ddc0dbf8.png)

**Comment by flukeout** [comment]
Looks like the changes only show up on the site for me when I'm signed in. When I sign out, they revert back to the original styling. Weird.

**Comment by flukeout** [comment]
OK - seems to work fine now. Closing! Let me know if you need any other changes etc, it's fairly easy to make small styling tweaks. I can also show you were to do it in the interface if you are comfortable with CSS etc.

cc @prefontaine

**Comment by prefontaine** [comment]
Brilliant! Thanks again, Luke <3
