### ISSUE TITLE
Give Matt admin permissions on this repo

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#13]
@prefontaine did you create this repo? Matthew and I can't seem to access the settings tab. It means I can't assign tickets, create labels, etc. Did you create the repo by chance? If so, can you give me admin permissions?

**Comment by prefontaine** [comment]
No I didn't. I thought you did.

**Comment by OpenMatt** [comment]
It was a 2-factor authorization issue. fixed.
