### ISSUE TITLE
Embed Hypothes.is into StoryEngine.io

### ISSUE THREAD

**Issue by ankuhl** [MozillaFoundation/Story-Engine#132]
We want Hypothes.is embedded on StoryEngine.io like it is on the [Internet health report ](https://internethealthreport.org/v01/open-innovation/)

Jeremy from Hypothesis said we can do that with a simple javascript. (Open tagging, although we can develop a system where some folks can jon the group so they can access controlled vocabulary.) See here: https://web.hypothes.is/for-publishers/#embedding. Reach out to @cade (tech dude) and @kasia (IH report person) on the Mozilla slack to see how they embedded and if they have a custom script — they tailored the styling.

**Comment by cade** [comment]
> tech dude

[Tech Man ... Tech MAN!](https://youtu.be/i2l4Wx9YZ1E?t=15s)

**Comment by cadecairos** [comment]
@ankuhl OK, hypothesis should now be embedded in all posts on storyengine.io (but not pages)

I added the necessary domains to the Content Security Policy, and added this function to the theme's `functions.php` to add the script to posts:

```php

function add_hypothesis() {
    if(is_single()) {
        wp_enqueue_script( 'hypothesis-script', 'https://hypothes.is/embed.js', [], false, true);
    }
}
add_action( 'wp_enqueue_scripts', 'add_hypothesis');
```

Let me know if it's working as expected, so we can close out this issue.

**Comment by ankuhl** [comment]
@cadecairos This is wonderful! All seems to be in working order, and we can close out this issue. Thank you!
