### ISSUE TITLE
Investigate "StoryThings" tool

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#15]
- Matt Locke runs Storythings. His company works with organisations to "use stories to solve problems"  http://storythings.com/
- deck explaining the tool: https://www.dropbox.com/s/rtff5ypl2mtz8bx/Outside%20The%20Bubble.pdf?dl=0
- Matt talking at a recent media conference in the Netherlands about streams and attention patterns: https://vimeo.com/172401769
- has World Wildlife Fund and Water Aid as clients 
- built a tool for them to get content direct from the field to enable them to tell better stories about their work.  
- These tools work on feature and smart phones and improve the content and the work flow management. 
- Sam Burton referred them to us
- Matt is meeting with them Friday just to see and explore

**Comment by OpenMatt** [comment]
- @xmatthewx @prefontaine let me know if you want to join?

**Comment by xmatthewx** [comment]
Glad to join @OpenMatt if schedules align.

**Comment by prefontaine** [comment]
@OpenMatt Any update on this... thinking for now we focus on interviews and put this to back burner.

**Comment by OpenMatt** [comment]
I met with the principal behind this -- no action items on it for now. Main takeaway was: we're going to investigate to see whether they might come join us at MozFest. And test their tool as a way to tell the story of the festival. 

But: it shouldn't create any dependencies or added complexity for our own work. It's more like: throw them into the swimming pool and see if they swim. If so, great. If not, no harm done. :) 

I'll follow up from here.

**Comment by OpenMatt** [comment]
Matt needs to follow up with them. On my to do list this week.

**Comment by OpenMatt** [comment]
Closing.
