### ISSUE TITLE
Incorporate impact stories into on-boarding 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#19]
Angela came up with an interesting use for this work -- to help explain what MoFo does to new hires across the org. 

No action items here for a while -- but filing so we don't forget. 

Even just good pull quotes that can be sprinkled through other docs, etc, help add empathy and understanding for what we do.

**Comment by prefontaine** [comment]
@OpenMatt LOVE IT!!!

**Comment by OpenMatt** [comment]
@MandyRawls given that you're working on updating our on-boarding materials now, we could provide you with a few inspiring impact stories of how our work effects real humans in the world, if you think that would be helpful?

**Comment by MandyRawls** [comment]
@OpenMatt apologies for the delay - was ooo last week. I think that would be incredibly helpful for both recruiting and onboarding. Please let me know if you need anything from me for the work. Thanks!

**Comment by OpenMatt** [comment]
great! we're working on it now.

**Comment by OpenMatt** [comment]
Mandy says: 
* We've added links to the story content in our onboarding handbook, and will also add it to our onboarding roadmap website that is being created. 
* Love the idea of incorporating interviewing a MoFo to learn their story into the process as well.

**Comment by OpenMatt** [comment]
@MandyRawls let us know if there's anything more we can do to help here!
