### ISSUE TITLE
Add issue tags to front end

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#2]
For easier tagging / sorting, etc

**Comment by OpenMatt** [comment]
@xmatthewx the issues tags to use are: 
https://docs.google.com/document/d/1cLC3zpcUaqqordvmHOTpcRUiyNqlBf1RIordVLZ9WIg
- Online Privacy & Security    #privacy
- Open Innovation        #open
- Decentralization        #decentralized
- Web Literacy            #weblit
- Digital Inclusion        #web4all

**Comment by OpenMatt** [comment]
@prefontaine see that google doc link above for short definitions of each

**Comment by prefontaine** [comment]
@OpenMatt Yes I was in touch with Sam already and added those to the tip sheet. Forgot to update here, though #doh!

**Comment by prefontaine** [comment]
@OpenMatt oh she did say the tags may change... but good for us for now

**Comment by OpenMatt** [comment]
Let's close this for now and re-open pending the decision we make here:
https://github.com/MozillaFoundation/Story-Engine/issues/7
