### ISSUE TITLE
Book Christine's travel for MozFest

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#21]
Working on it.

**Comment by OpenMatt** [comment]
cc @chrislarry33 @prefontaine

**Comment by OpenMatt** [comment]
From Sarah: For christine you will need to add her as a guest to your egencia account, pamela can help her, and then book her flights for her.

I have captured Christine for you in the hotel room allocation but she will need to fill out the travel form as per staff travel email https://mzl.la/MozFesttravelform

**Comment by OpenMatt** [comment]
For Hawaii: Matt will update this ticket asap.

**Comment by OpenMatt** [comment]
@prefontaine : are we all set? did you complete your travel plus fill in the form?

I'll file a separate ticket for Hawaii

**Comment by OpenMatt** [comment]
@prefontaine can we mark this one closed?
are you all set?

**Comment by prefontaine** [comment]
Waiting to hear back from Pam as I cannot confirm flight. Submitted form
for hotel.

**Comment by OpenMatt** [comment]
any news on this one?

**Comment by prefontaine** [comment]
Flights ok. Hotel not yet confirmed. Thanks for checking!

**Comment by OpenMatt** [comment]
@Saallen any news on Christine's hotel?
