### ISSUE TITLE
Discuss our interview transcription service / process

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#23]
@prefontaine is there a particular service you're using? I've used CastingWords in the past. 
http://castingwords.com/

($1 / minute)

**Comment by prefontaine** [comment]
@OpenMatt I'm not transcribing -- typing really fast and then sending to interviewee to clarify and approve (see Methodology on this, want it to express what they want to say vs verbatim of our convo).

**Comment by OpenMatt** [comment]
hm! ok. in our next weekly, let's talk about whether sending an audio file to a transcription service might help the process.

**Comment by prefontaine** [comment]
Sure thing. Pros are that it can be a bit easier for the conversation to flow. Cons are that transcriptions often require massaging. From my experience interviewing innovators at the bank I ended up going with simultaneous typing. That did not work with all interviewers though. You gotta type fast :)

**Comment by OpenMatt** [comment]
This is mostly done -- just need to approve budget w. Chris once he's back from vacation

**Comment by OpenMatt** [comment]
Our transcription budget for 2017 will be capped at $1000.

**Comment by OpenMatt** [comment]
we can close this once we get approval from Chris

**Comment by OpenMatt** [comment]
approved
