### ISSUE TITLE
Do interview(s) focused on combatting trolls / making the internet more civil / inclusive

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#24]
As part of bringing our "digital inclusion" issue to life, look for a leadership network / advocacy community member who is:

a) contributing to Mozilla's / New York Times "Coral" project
b) doing something else that's inspiring on this front 

See for context:  this week’s Time magazine by Joel Stein: 
Why We Are Losing the Internet to a Culture of Hate http://time.com/4457110/internet-trolls/

And: 

Columbia Journalism Review/Nausicaa Renner who wrote an article on Mozilla’s own Coral project in response to the recent news that NPR is shutting down its comments section articles (for why they decided that see above article):

As sites abandon comments, the Coral Project aims to turn the tide: http://www.cjr.org/tow_center/improving_audience_engagement_coral_project.php

It would be good to interview and probe some of our existing members about:
a) why this issue matters (in their own words)
b) novel / innovative approaches they're taking to work on it
c) the value (if any) they see / are getting from Mozilla's network here -- and how we could do more. 

Thoughtful reading that both starkly frame the issues while also providing potential solutions. 

@chrislarry33 says: "Had me thinking about what a campaign would look like to fight for the positive culture of the web that battles these trends."

cc @prefontaine @KevZawacki 

plus @amirad in case she has ideas for interesting people to talk to here...

**Comment by OpenMatt** [comment]
Could be: Lilah Raptopoulos, community manager at the Financial Times
- "She is not officially affiliated with Coral, but she participated in some of Coral’s initial brainstorms."
  http://www.cjr.org/tow_center/improving_audience_engagement_coral_project.php

**Comment by prefontaine** [comment]
@OpenMatt I went to [Mozfest session on Coral last year](https://app.mozillafestival.org/#_session-572). Cannot find the etherpad. Would some of the folks who ran that be good candidates? I will look at Lilah. Ideally the person would see themselves as affiliated in some way with Mozilla. (also: Funny I was just reading that article on NPR comments this morning, via Sean Bonner, whom I met several Mozfests ago. Full circle.)

**Comment by prefontaine** [comment]
@OpenMatt... Thinking more... One person to ask for leads (or even interview) might be Willow Brugh. She's been doing work on this called "Weaponized Social". Thoughts?

**Comment by OpenMatt** [comment]
yes to both. good ideas.

**Comment by prefontaine** [comment]
I'll reach out to them. Also looks like Sarah Jeong is a good candidate: https://app.mozillafestival.org/#_session-343

**Comment by OpenMatt** [comment]
Already starting to line up candidates at MozFest like this is a great idea.

**Comment by prefontaine** [comment]
@OpenMatt I sent Sydette an interview request but not sure about her email. I see online that she says she works with Coral/Mozilla. Does she have a Mozilla email?

**Comment by OpenMatt** [comment]
@prefontaine sorry I'm not sure who Sydette is

**Comment by OpenMatt** [comment]
@prefontaine let me know if you need more help / are blocked on this one

**Comment by OpenMatt** [comment]
@prefontaine let's discuss next steps in our stand-up

**Comment by prefontaine** [comment]
I would like some more leads in this direction, but let me see if there are
more in the sources I have prioritized before I reach out for more help on
this.

**Comment by OpenMatt** [comment]
Christine has interviewed:
- Sydette
- Willow
- Emily May
- Hera (tmrw)
