### ISSUE TITLE
Interview tips from Grants team

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#26]
(from Amira & Julia's work with the UN Women-funded project in Nairobi and Cape Town)
https://forum.learning.mozilla.org/t/mozilla-clubs-case-studies/962

Two of our three Regional Coordinators for the project (the two based in South Africa) have been nominated for what we believe is a fairly prestigious award http://www.itweb.co.za/index.php?option=com_content&view=article&id=155098
(all of the RC's -- Mmaki Jantjies, Baratang Miya and Hildah Nyakwaka --  are remarkable, don't know if you or Christine had the chance to chat with them in London)
. 
it might be useful/relevant if you are collecting data on leadership development (in addition, one of the Club Captains associated with the project has been promoted at work as a reflection of her work with Mozilla Clubs, Peggy is included here, but not her promotion story https://thimbleprojects.org/juliavallera/70909/

**Comment by OpenMatt** [comment]
@prefontaine some good ones here! see what you think

**Comment by OpenMatt** [comment]
need to prioritize this versus the others

**Comment by prefontaine** [comment]
Mmaki was already on my list. Great great interview. Wow. And she recommended I speak to Baratang, that is set up for Thursday (I ask folks who else I should speak to — snowball sample). I'll follow up with the others.

**Comment by anmechung** [comment]
- [ ] 1) Kylee Durant
  Mozilla's partnership with RP/6 to train veterans, military families and personnel on web literacy:
  https://medium.com/read-write-participate/digital-skills-on-the-path-forward-56f3291cfe9#.os8hxs99a  I would recommend interviewing Kylee Durant COO at RP/6
- [ ] 2) Pull from NSF report
  Lindsey just submitted a great report to NSF about successes and lessons learned to date - you might want to reach out her to see what stories might be possible. 
- [ ] 3) the New World of Work
  An interesting remix of our 21C Skills (they reference Mozilla in their remix and keep us abreast of their progress): The [New World of Work](http://www.newworldofwork.org/) is funded by the California Community College Chancellor's Office Doing What Matters initiative and collaborates with employers, workforce development boards, educators, and research organizations across the country to build 21st Century Employability Skills. 
- [ ] 4) Randy McDonald
  a volunteer who came to London's All Hands is in the midst of starting 10 Mozilla Clubs for youth in Oregon.  
- [ ] 5) Michigan Dept of Education
  The Michigan Department of Education is the first state to partner with community orgs such as   Michigan’s After School Partnership, Michigan State University’s 4H Extension Program, and the Michigan Association of United Ways to use badges to capture learning in out of school time spaces and make it count towards credit/competency-based learning.  We're working on a blog for this and will add here shortly.

**Comment by OpenMatt** [comment]
This is outstanding! Thank you An-Me!

**Comment by prefontaine** [comment]
Amazing. Thank you so much. Looking forward to talking to all of these
folks!

**Comment by LindseyInCHA** [comment]
@OpenMatt  Here's the NSF report: https://docs.google.com/document/d/1_NkrUUK2ZS46_dYlptQoK36HwgzD2YNxAJMUXsmHCIM/edit#

**Comment by OpenMatt** [comment]
Thank you!

**Comment by prefontaine** [comment]
Oh... one more thing... An-Me please keep me posted on the Michigan
Department of Education initiative. Also, I cannot access the NSF report —
have sent a request via Googledocs. Thank you!

**Comment by OpenMatt** [comment]
@prefontaine status?

**Comment by prefontaine** [comment]
From Amira & Julia's work... I have interviewed Mmaki Jantjies and Baratang Miya. I still need to reach out to Peggy and Hildah Nyakwaka.

For An-Me's team, I've interviewed Kylee Durant and am about to post that. Very good interview! For the rest I'm sending via email.

**Comment by OpenMatt** [comment]
Ok. @prefontaine I think these are probably already logged in the interview queue, so I'm going to close.

**Comment by prefontaine** [comment]
These are in my email... but need to add to queue. Almost done!
