### ISSUE TITLE
Pull interview leads from the Chronicle

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#28]
https://docs.google.com/document/d/13C7TC3U9LZMf8fl5njsi0fZfx2pulLBpt08u3LIdNBk/edit

@prefontaine can evaluate this to see:
a) whether these can be imported and tagged as is, or
b) flag for follow-up interviews as needed

**Comment by OpenMatt** [comment]
@prefontaine it would be good for us to prioritize these various input sources together, so we know which ones to focus on first -- pre MozFest

**Comment by prefontaine** [comment]
These are done and added to the spreadsheet. Some have been interviewed.
