### ISSUE TITLE
Schedule interviews with a select number of MozFest session leads

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#29]
https://github.com/MozillaFoundation/mozfest-program-2016/issues

blocked on: waiting for Sarah to give us the green light, once they have been accepted

**Comment by OpenMatt** [comment]
@Saallen any updates on this one! We're excited for MozFest. :)

**Comment by Saallen** [comment]
Hey- YES! 🚦 
Every issue open on github has now been accepted. How can we set you up for success here?

**Comment by prefontaine** [comment]
@Saallen Awesome! Maybe I should simply go through the issues and pick the folks I'd like to interview. The leads I've been following so far have been quite responsive — even though my emails come out of the blue — so, if it is okay with you, how about I reach out to folks directly, letting them know how I learned about them. Of course, I'm happy to send you a list beforehand if you'd like to reach out to them first to give a heads up. Open to other suggestions, too :)

**Comment by Saallen** [comment]
@prefontaine happy for you to continue to contact as you see fit

**Comment by prefontaine** [comment]
Thanks @Saallen. @OpenMatt you can remove the "blocked" tag — for some reason Github is not letting me edit the issue. I now have two-factor authentication.

**Comment by OpenMatt** [comment]
next step: @prefontaine will review and develop a target list of session leads we most want to interview
