### ISSUE TITLE
Ask Sam Dyson for Hive Chicago interview leads

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#30]
with an emphasis on: pulling from work they've already done, blog posts already written, etc.

e.g., explore whether we can pull from existing assets, as opposed to just a list of names. To leverage any good work they've already done in this area.

**Comment by prefontaine** [comment]
Email sent to Sam.

**Comment by prefontaine** [comment]
I'm closing this because we have evolved to focus on other areas. Also we have interviewed two Hive Chicago folks.
