### ISSUE TITLE
Make sure Christine + Matt have microphones for MozFest

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#32]
What we need: 3 x lavalier microphones

**Comment by OpenMatt** [comment]
brett's on vacation til next week I believe. we can let this sit til he's back.

**Comment by OpenMatt** [comment]
Matt will try to talk to Brett today

**Comment by OpenMatt** [comment]
we're going to forget about video -- and just focus on capturing audio.

**Comment by brettgaylor** [comment]
I have one wireless mic and digital audio recorder, if you want.

**Comment by OpenMatt** [comment]
I do! Thanks Brett.

**Comment by OpenMatt** [comment]
I've got my microphone all set. Christine, do you?

**Comment by OpenMatt** [comment]
@brettgaylor are you able to bring that mic for us to use? thanks!

**Comment by OpenMatt** [comment]
Christine has a lavalier mic -- Matt will bring two more.

**Comment by brettgaylor** [comment]
Sorry for delays - do you need audio recorder and lav mic?

**Comment by OpenMatt** [comment]
Hey Brett. If you have an extra lav mic, that'd be great!

**Comment by brettgaylor** [comment]
OK I'm going to bring a sennheiser wireless mic and receiver, a sony powered shotgun mic, a ZOOM audio recorder and various doo-dads.  My wireless doesn't have a clip so you might need to get creative.

**Comment by prefontaine** [comment]
thank you!
