### ISSUE TITLE
Interview Gina Grant

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#38]
via Chad Sansing

Chad recently worked with Gina Grant (ggrant@architecture.org) of the Chicago Architecture Foundation to adapt an activity from last year's MozFest for our teaching activities on https://learning.mozilla.org/activities. 

Dorine Flies, of [MozFest] Youth Zone fame, put us in touch. Gina and I have been helping CAF devs revise the activity and migrate it into our new curriculum template.

It's an example of a high-end collaborative outcome catalyzed by MozFest, our curriculum work, and the CAF's involvement with Hive Chicago.

Chad can ship you a link to the activity when we push it to production.

**Comment by OpenMatt** [comment]
@prefontaine remind me: did we interview her already?

**Comment by prefontaine** [comment]
Yes! She is awesome.

**Comment by prefontaine** [comment]
ugh. I still can't close an issue.... grrr...
