### ISSUE TITLE
Feed stories into Pulse + Medium streams 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#39]
work w. @KevZawacki on this later this month.

**Comment by OpenMatt** [comment]
There are two key streams for us to feed into
- Read, Write, Participate (web literacy + inclusion) https://medium.com/read-write-participate
- Advocacy https://medium.com/mozilla-advocacy

**Comment by KevZawacki** [comment]
Hi @OpenMatt, following up... any story engine pieces ready for publication?

**Comment by prefontaine** [comment]
Hi @KevZawacki. Not yet ready for publication, as far as I know. But we are adding more and more stories here: http://storyengine.io/category/stories/. This is the raw material to craft the pieces for Medium. It is open content.

**Comment by OpenMatt** [comment]
@KevZawacki I'm going to turn some of those raw interviews into more polished stories and share with you next week.

**Comment by OpenMatt** [comment]
I'll get one or two stories to @KevZawacki this week.

**Comment by OpenMatt** [comment]
@KevZawacki I have failed at this, but am determined to get this done this week.

**Comment by KevZawacki** [comment]
@OpenMatt Thanks for the update -- looking forward!

**Comment by OpenMatt** [comment]
@KevZawacki I know @prefontaine will be touching base w. you guys re: best way to work with Comms + Marketing going forward. But in the mean time, there's tons of content for you to peruse and full from, sorted by topic, at https://storyengine.io/
* Most of these are long-form interviews. They could easily be polished and cut down.

**Comment by prefontaine** [comment]
@KevZawacki please let me know when is a
good time to connect. Just a heads up that this story has gotten a lot of
traction on social media:

https://storyengine.io/stories/open-innovation/christie-bahlai/

Now, as part of our production process, we send a notice to interviewees
when we've posted their edited transcript, along with the copy we're using
to promote via Twitter. Do you want to be copied on these emails?

**Comment by prefontaine** [comment]
BTW going to close out this thread as it will get discussed under #89.
