### ISSUE TITLE
Update our consent form and streamline consent UX

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#40]
To radically simplify to something like:

"I understand that all Mozilla Network stories are shared under the CC-BY-SA license. And I'm cool with that." 
-  whatever additional legal-ese or copy is required. 

(agree check box) 

And then just link to the CC-BY-SA  license details. 
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by OpenMatt** [comment]
@prefontaine will start by drafting copy here first

**Comment by OpenMatt** [comment]
let's make this a P1 since it will simplify potential issues we encounter later in the process / as we gather more stories

**Comment by prefontaine** [comment]
Done. But it's not radically simple... I actually added a piece. Open to
discussing making radically simple. But I'd want to know the risks to doing
that.

**Comment by OpenMatt** [comment]
I'm not sure where to see the latest consent form. 

Is it this link? I don't see any changes on it. 
https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSfANu2fd4diQ7bDqDnEEXlaDnow8NIhK3P89sbRpZNRUUDvsg/viewform?c=0&w=1

**Comment by OpenMatt** [comment]
I guess I'm also a bit unsure of how the consent UX works, between the google form and the google doc
https://docs.google.com/document/d/1VAA-Hhp6zdyGhkVmwEbaqf5UjhSjyVgLC5yta3OspUA/edit

Can we simplify / streamline the overall process for how we present and receive consent for users?

**Comment by prefontaine** [comment]
Oooops that was an artifact from the testing phase. I've removed the link to the form. We should, however, have some printed out for Mozfest. The only change would be ability for parents to sign for minors.

**Comment by prefontaine** [comment]
Matt I'm open to streamlining this further. But if it is okay with you the way it is then we can close this ticket.

**Comment by OpenMatt** [comment]
Let's mark this done for now, continue testing with interviewees, and re-visit in October to see what we learned
