### ISSUE TITLE
Schedule interviews / make a plan for interviewing MozFest speakers

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#41]
- @KevZawacki will be in touch once the time is right

**Comment by OpenMatt** [comment]
- @prefontaine nothing to do here yet, but a good idea from Kevin to interview some of the high-profile speakers / execs etc. who will be appearing at MozFest
- as with session leads, we'll want to be sure to carefully respect Kevin & Sarah's process with these high-value relationships, and wait til we get the green light before emailing these speakers  / reaching out

**Comment by prefontaine** [comment]
Absolutely. This should be to support those relationships and Mozfest...
not get in the way :)

**Comment by OpenMatt** [comment]
@Saallen any updates on this one? Just checking in!

**Comment by KevZawacki** [comment]
We're learning our speakers are a pretty busy bunch -- it's hard enough extracting a bio and headshot.

We may be able to capture interviews on-site, but I don't think pre-MozFest interviews are in the cards.

**Comment by OpenMatt** [comment]
ok makes sense -- thanks Kevin.

what's the best process from your perspective for trying to schedule an
on-site interview with these folks in advance? (and also: let us know if
you want to work with us on the interview / do the interview / etc.?)

**Comment by KevZawacki** [comment]
@OpenMatt I think the best bet is spending time in the D+D area during the talks. Speakers will be there before and after their talks, and would happily (I presume) chat.

**Comment by OpenMatt** [comment]
great. what's D+D area again?

**Comment by KevZawacki** [comment]
Walker Room (first floor)

**Comment by OpenMatt** [comment]
@prefontaine : Here's more information plus speaker's list: https://medium.com/mozilla-festival/everything-you-need-to-know-about-mozfests-speaker-series-af8eb8f186bf#.7nm3xed68

Zeynep Tufekci // @zeynep
Professor, University of North Carolina. Contributor, New York Times
On Digital Inclusion and Decentralization
Speaking Saturday, Oct. 29 at 11:15 a.m.

Brian Behlendorf // @brianbehlendorf
Executive Director, Hyperledger Project
“Bringing Back the Decentralized Web, with Blockchains and Other New Tools”
Speaking Saturday, Oct. 29 at 11:15 a.m.

Maggie Vail // @magicbeans
Executive Director, CASH Music
On Web Literacy
Speaking Saturday, Oct. 29 at 11:15 a.m.

Sahar Aziz // @saharazizlaw
Professor of Law, Texas A&M University
On Mozilla’s key issues
Speaking Saturday, Oct. 29 at 1 p.m.

Katherine Maher // @krmaher
Executive Director, Wikimedia Foundation
On online harassment
Speaking Saturday, Oct. 29 at 3:15 p.m.

Chris Soghoian // @csoghoian
Principal Technologist & Senior Policy Analyst, ACLU
On privacy and security
Speaking Saturday, Oct. 29 at 3:15 p.m.

Ashe Dryden // @ashedryden
White House Fellow. Programmer. Diversity & Inclusion Consultant
“The Ethics of Unpaid Labor and Open Source Software”
Speaking Saturday, Oct. 29 at 3:15 p.m.

Volker Birk
CTO, pretty Easy privacy. President, p≡p Foundation Council
On privacy and security
Speaking Sunday, Oct. 30 at 12:15 p.m.

Simone Browne
Professor, University of Texas at Austin
On Privacy, Security, and Digital Inclusion
Speaking Sunday, Oct. 30 at 2 p.m.

Eliot Higgins // @EliotHiggins
Founder, Bellingcat & Brown Moses Blog. Research Associate, King’s College London
“The End of Secrets: Conflict in the Engagement Age”
Speaking Sunday, Oct. 30 at 2 p.m.

**Comment by OpenMatt** [comment]
@prefontaine this one might be about scheduling time into our place to button-hole these people before or after they speak.

**Comment by prefontaine** [comment]
Hey @OpenMatt @KevZawacki @Saallen — getting down to the nuts and bolts of scheduling speakers and participants. We're generally asking folks to meet us in back of the 5th floor (see https://calendly.com/christine-prefontaine/storyengine-mozfest/). I am wondering if it is possible to send speakers a heads up so that we can book and block off their interview times (they run about 45 minutes). I can make a separate Calendly invite just for speakers, changing the location. I'm happy to come to the D+D area for scheduled interviews if that is easier for speakers. @OpenMatt — we could tag team on these.

**Comment by KevZawacki** [comment]
Hi @prefontaine,

I'm currently chasing down a handful of outstanding items from our speakers (legal releases, slide shows, talk titles), and so am reluctant to add another ask.

Our best bet is to hang out in the Speaker Series space and grab them shortly after their talk.

**Comment by prefontaine** [comment]
Hi @KevZawacki. Totally understand. Thanks very much!

**Comment by prefontaine** [comment]
Hi @KevZawacki. An update: We've talked it through and decided better to request the StoryEngine interview after Mozfest. As a follow up. Grabbing one of these folks for a full 30-45 minutes right after they talk may not feel good to them. Plus, after they'll have the experience of being at Mozfest to reflect on.

**Comment by prefontaine** [comment]
Do you think we need to adjust questions for these folks? Not sure about
their level of involvement as part of the Mozilla network — vs being
luminaries that we're bringing in.

Also... I'd like to block off the times to meet each one of them. Wondering
if that can be done in alignment with their talk. Say, book them 30 minutes
after their session? Thoughts?
