### ISSUE TITLE
Hand over raw transcripts to Matt

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#42]
So that Matt can work on them while Christine's away.

**Comment by OpenMatt** [comment]
best process would be: Matt cleans them up and then sends to Christine

**Comment by prefontaine** [comment]
Hi Matt. I'm sending you transcripts via email.

**Comment by OpenMatt** [comment]
I didn't have time to do anything with these last week. Too busy w. 2017 planning. Let's mark closed.
