### ISSUE TITLE
Update credit card info on Casting Words

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#48]
So that it gets billed directly to Mozilla, instead of to Christine. 

@chrislarry33 can you maybe provide @prefontaine with a card to use?

**Comment by OpenMatt** [comment]
@prefontaine you should have what you need to close this now?

**Comment by OpenMatt** [comment]
@prefontaine good to go?

**Comment by prefontaine** [comment]
I think so. I have the info and am going to post a bunch of audio files
today.

**Comment by prefontaine** [comment]
All good. You can close this.
