### ISSUE TITLE
Email interview invitation to "recognition list" members

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#49]
- Christine's standard outreach email should be fine. 
- Combined with: "hey are you going to be at MozFest? If so we'd love to interview you in person. Please go here [link] to schedule a time?"

**Comment by OpenMatt** [comment]
@prefontaine will try to get these out today / tmrw

**Comment by prefontaine** [comment]
I will put that list of folks into the StoryEngine tracker spreadsheet --
so that we can track who has responded, etc.

**Comment by prefontaine** [comment]
This is done.
