### ISSUE TITLE
Create a simple web page documenting our MozFest work + how to help

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#52]
Including: instructions for interested staff / volunteers

**Comment by prefontaine** [comment]
@OpenMatt I started by making the interview question page more robust — including some scripts and instructions: http://storyengine.io/interview/. Next, I'm going to create a Mozfest page on StoryEngine and then link to this. Thoughts?

**Comment by prefontaine** [comment]
And here's simple web page: http://storyengine.io/mozfest2016/
