### ISSUE TITLE
Ensure we have a quiet-ish space to interview

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#54]
@Saallen @KevZawacki  : is there someplace close to the Comms area that we can use to do interviews? We will need two separate / relatively quiet spaces we can use to interview people.

**Comment by Saallen** [comment]
@OpenMatt back of the 5th floor is a good option

**Comment by OpenMatt** [comment]
Thanks @Saallen !

**Comment by prefontaine** [comment]
Is there a map of the interior that I could point folks to? Or a photo --
see attached, is this the right place? I've found that's worked well in the
past — with buildings simpler than Ravensbourne. Lots of folks will have
been there before... but for the new folks might be helpful.
