### ISSUE TITLE
Update storyengine.io WordPress theme

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#59]
@prefontaine I'd like to use the same theme as http://blog.workopen.org/ 

because it emphasizes big splashy photos that I think will bring the stories to life more.
Plus: is consistent with the look and feel of other MoFo sites, like mofo.build. 

But before I do that: want to discuss? Will changing the theme mess w. any of your needs?

**Comment by prefontaine** [comment]
happydance
