### ISSUE TITLE
Create interview list queue for August / Sep

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#6]
Prioritize story tips that could be turned into something that aligns with State of the Web

**Comment by OpenMatt** [comment]
@prefontaine : where do we want to track who we're planning to interview next? Should we just add a column to the tips spreadsheet?
- July priorities: focus on web literacy stories that have communications potential. so that we can submit them for consideration to State of the Web
- Plus: copyright. There's a NY educator in there doing interesting work around remix / copyright. That could be a nice compliment to the copyright campaign we're going to run this quarter.

**Comment by OpenMatt** [comment]
@samanthaburton any updates on timelines for your story selection process? I know we may be running up against your deadline soon. Let us know if additional interviews / stories from us would still be helpful for State of the Web?

**Comment by samanthaburton** [comment]
Hey @OpenMatt. Sorry I wasn't aware of this ticket! @KevZawacki and Kevin Fann from marketing have been leading on story creation, and we have a pretty solid idea of what stories we're moving forward with - there's a brief overview in the latter half of this deck: https://docs.google.com/presentation/d/1XXzQd4ZAXvRzgFwBg6HgZ5NTbVmFxTk0g34YUNnRU7I/edit#slide=id.g14d9341884_1_137

@KevZawacki would you be able to touch base w/Matt to see if there's anything we'd like to add into the story engine process?

FYI that deck is from an update from Janis, Chris & I to Mark, Jascha, Mary Ellen, Alex Salkever and Denelle, so if anything could use more context please let me know!

**Comment by OpenMatt** [comment]
perfect, thanks Sam. and no worries — we just wanted to try and pitch in if it was still useful. 
but sounds like you guys are all squared away.

Christine, let’s document our “interview queue” anyway, so that we can make choices about who we want to prioritize / areas we want to test / learn, etc.

**Comment by prefontaine** [comment]
@OpenMatt got it. I've sent Sam a request to for access to the SOW deck.

**Comment by samanthaburton** [comment]
@OpenMatt @prefontaine just gave you access, but the most recent version is now here: https://docs.google.com/presentation/d/1tBdDs1-mG1oOM4ERQ9dSfqPziVDh-vLXikn-xuWLA2A/edit#slide=id.gd58133b56_0_69

**Comment by prefontaine** [comment]
@samanthaburton Thanks much!

**Comment by OpenMatt** [comment]
@prefontaine I think this ticket is our P1 right now -- we want to make sure we have a clear hit list / queue of folks we want to interview in rest of Aug / Sep. And ensure you feel like it's rich / meaty / diverse enough. And that you're fired up to work on it! (e.g., that those folks seem right / feel good to you.) 

I'd suggest the easiest way is just to highlight rows in our tip spreadsheet. Then we can review together in our next weekly? 

The importance of SoW has probably passed for us. Though it's great context for us to be aware of, in terms of another way we're using personal stories to bring our issues to life. And also: some of the great facts in there help open ideas for follow-up interview questions / angles. 

(Thanks for sharing that doc @samanthaburton -- there's great work in there. Love it.)

**Comment by samanthaburton** [comment]
Quick question - are you aware/following up with the Chronicle project, which I believe was led by Ben & Kevin? It was put on hold a few months ago, but I just came across some stories again and it struck me that it's probably v. relevant - if it's not on your radar, let me know and I'll send more notes etc via email

**Comment by prefontaine** [comment]
@OpenMatt to discuss when we touch base tomorrow. Thanks, @samanthaburton!

**Comment by OpenMatt** [comment]
@samanthaburton yes! I was aware of it -- but lost contact. Do you have a link / somewhere we can see & pull stories?

**Comment by samanthaburton** [comment]
There are the two docs I've seen, @KevZawacki will likely know more!
https://docs.google.com/spreadsheets/d/1Kai28T3rdKqT6fNxqY7InBQy1WJA701lKjxYs50wpRM/edit#gid=1698045351
https://docs.google.com/document/d/13C7TC3U9LZMf8fl5njsi0fZfx2pulLBpt08u3LIdNBk/edit

**Comment by KevZawacki** [comment]
Yep, @samanthaburton's second link contains all Chronicle stories

**Comment by OpenMatt** [comment]
ok great! Christine, maybe you can read through those, pull any relevant
stories and then code and tag them on the site.

**Comment by OpenMatt** [comment]
- goal is to schedule 3 interviews per day
- need to get more tips into queue
- let's start by looking at those Chronicle stories 
- plus: let's start mining the MozFest session organizers + speakers

**Comment by OpenMatt** [comment]
Priorities for interview queue: 
1) mine the Chronicle
2) mine accepted MozFest proposals https://github.com/MozillaFoundation/mozfest-program-2016/issues
3) check in w. grant fundraising time (Matt will email) 
4) ask Sam Dyson for Hive Chicago leads / tips (Christine will email) 
5) ask Simona for Hive Toronto leads (Christine will email)

**Comment by OpenMatt** [comment]
I'm going to break those 5 items above into separate tickets

**Comment by OpenMatt** [comment]
Closing this now, as all the others have been filed as separate tickets
