### ISSUE TITLE
Publish fellows interviews

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#60]
List fellows interviews we’ve already done: 
- [x] Christine Zhang, Open News Fellow
- [x] Eva Constantaras, her org is hosting an Open News Fellow in Kenya
- [x] Kristie Whitaker, Open Science Fellow
- [x] Christie Bahlai, Open Science Fellow

**Comment by OpenMatt** [comment]
@prefontaine let's update this one when we have a sec

**Comment by OpenMatt** [comment]
@prefontaine should we mark this closed?

**Comment by prefontaine** [comment]
@OpenMatt Not yet.

**Comment by OpenMatt** [comment]
@prefontaine any updates?

**Comment by prefontaine** [comment]
Next action here is to interview folks we have not yet. @ankuhl and I will organize these next week.

**Comment by prefontaine** [comment]
This is ongoing so I'm going to close it.
