### ISSUE TITLE
Update interview questions

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#61]
- [ ] 1) Up-level “Privacy and Security” (based on messaging document / talking points?) 
- [x] 2) Ask about “internet health” 
- [ ] 3) What are you working on? Tell us more about your project. (And: how people can collaborate / benefit from it / get involved?) — what is the benefit of your project for other people? If you had 10 skilled smart volunteers tomorrow what would they do?

**Comment by OpenMatt** [comment]
* Next steps: 
** @prefontaine will do (1) 
** Plus tweak to: "What role does 'open' play in your work? Why does it matter to you personally?"
** Add "10 skilled contributors" question
** maybe update the "how might this be useful to you" quesiton

**Comment by prefontaine** [comment]
Okay it's down to 10 questions with a final "anything more?". I've tested these. I see above you had a slightly different approach on the open question. Hmmmmm. http://storyengine.io/interview/

**Comment by prefontaine** [comment]
Oh... and I went through the privacy/security docs but the question I came up with didn't flow. Stay tuned.

**Comment by OpenMatt** [comment]
@prefontaine I forgot -- what do we still need to do to update our documentation on this one again?

**Comment by prefontaine** [comment]
I updated this a while back. What's on the site now is current. What may be missing is something around privacy/security. I didn't have any major inspirations after reviewing the messaging docs... can we put this to P2 and discuss together?
