### ISSUE TITLE
Test "How to do a StoryEngine interview" documentation

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#62]
* Point staff interviewers at the documentation and tools they need
* Add a “how to interview” page to storyegine.io.
* And includes stuff like the value of calend.ly, how to record, how to transcribe, etc.

**Comment by OpenMatt** [comment]
Needs feedback.

**Comment by prefontaine** [comment]
Testing with Paul and Abdoul: https://storyengine.io/interview/

**Comment by OpenMatt** [comment]
@prefontaine did we get any feedback from those guys on how it wehnt / how we should improve the docuemntation or overall experience?

**Comment by prefontaine** [comment]
I checked in with them last week and they're still in the process.

**Comment by OpenMatt** [comment]
Going to mark this one done.
