### ISSUE TITLE
Deliver MLN web site package 1.0

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#65]
* @xmatthewx is offline this week, back next week
* We have a weekly mtg scheduled w. him, starting Jan 17
* Let's make sure we have an updated "package" of content waiting in his inbox at the end of this week, so that we have something concrete to review together in our first meting. 
* Main deliverable: 
- [ ] up to date set of posters / hero cards (with a name, quote, photo, etc.)
https://docs.google.com/presentation/d/1dBNsFQ-z4FCUGo3x91MofjE6fyNP0Y6Xzx4iGaOHSn0/edit?usp=sharing

Optional:
- [ ] entered into Pulse
- [ ] with a link through to a completed story where we have it. 
- [ ] and a clear plan / status on approvals for each

**Comment by OpenMatt** [comment]
Next step:
* add a comment to each slide indicating approval status. 
** - [ ] Matt
** - [ ] @prefontaine 
* review w. @xmatthewx to see if this is what he needs
https://docs.google.com/presentation/d/1dBNsFQ-z4FCUGo3x91MofjE6fyNP0Y6Xzx4iGaOHSn0/edit?usp=sharing
* add links through to projects

**Comment by prefontaine** [comment]
All of these are approved for content. Still waiting on a few photos. Am now going through to add links to posted stories.

**Comment by OpenMatt** [comment]
All of this work is now happening in these two tickets:
https://github.com/mozilla/network/issues/6
https://github.com/mozilla/network/issues/5

So I'm going to close this one.
