### ISSUE TITLE
Have staff conduct test StoryEngine interviews

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#67]
All the documentation on how to do it is here: http://mozstoryengine.wpengine.com/interview/

Potential people for us to recruit plus test with:
- [ ] Vanessa
- [ ] Insights Team (Paul + Abdoul)
- [ ] @KevZawacki ?
- [ ] @Lottarao ?
- [ ] @ldecoursy  ?
- [ ] @KGorr ?
- [ ] send out a general call for volunteers to all MoFo?

**Comment by OpenMatt** [comment]
Blockers to getting started: 
- [ ] updated interview question list
- [ ] suggested interviewees

**Comment by OpenMatt** [comment]
@prefontaine will indicate good potential interviewees in blue
https://docs.google.com/spreadsheets/d/1zeh03mqfHpClO1ijySAUvDZvq_fYARqtGwT0MPmp3EU/edit#gid=1443754482

**Comment by OpenMatt** [comment]
Plus: @prefontaine: can you paste the email copy to use here: 
https://docs.google.com/document/d/1K1nF4SakQ3-yphxqFvnCY0Dcf3BvXsFtVeY0hnJv2mA/edit

**Comment by prefontaine** [comment]
@OpenMatt you beat me to it :)
Note that folks will need to ask for me permission to access the googledoc because it has PII in it.

**Comment by OpenMatt** [comment]
k no worries. will just tell them to request access.

**Comment by OpenMatt** [comment]
Kevin and Abdoul have agreed to be test subjects! @prefontaine is getting them set.

**Comment by OpenMatt** [comment]
next step: get Kevin + Abdoul set. Then: see if others want to start interviewing as well. 

@KGorr do you have any interesting in interviewing a Mozilla network member? :)

**Comment by OpenMatt** [comment]
All the documentation on how to do it is here: http://mozstoryengine.wpengine.com/interview/

**Comment by OpenMatt** [comment]
@chrislarry33 @ldecoursy @samanthaburton let us know if there are any other staff or volunteers you would like us to reach out to / help train on how to do StoryEngine interviews?

**Comment by samanthaburton** [comment]
@OpenMatt can you share a bit more re: next steps for StoryEngine? Would help me identify people who'd make sense to train!

**Comment by prefontaine** [comment]
@samanthaburton Apologies for delay on your questions. Let me check in with @chrislarry33 when he's back and I'll have a better answer for you. For now, we're focused on processing/posting interviews, making sure that @xmatthewx has what he needs, and systematizing the process (how to do an interview, how to process an interview, etc.) — all to make it easy for others to generate stories.

**Comment by prefontaine** [comment]
Closing this because because duplicates #62. @samanthaburton I'll update you when we're able to check in — hopefully after March 14.
