### ISSUE TITLE
Publish Hawaii report

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#69]
Once we have approvals done

**Comment by prefontaine** [comment]
Emails reminding folks we need approvals sent.

**Comment by prefontaine** [comment]
I have almost all approvals. Do you want to make any edits to the latest version? Shall I send you a PDF?

**Comment by OpenMatt** [comment]
this is incredibly exciting! no, I have no edits to make.

let's just go ahead and post it to the web site when you think it's ready
:)

**Comment by prefontaine** [comment]
@OpenMatt could you please send me the original art for the cover so I can update it? Need to remove the "internal use only" language.

**Comment by OpenMatt** [comment]
@prefontaine can we mark this one closed?
