### ISSUE TITLE
Email StoryEngine participants to test network names

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#74]

**Comment by OpenMatt** [comment]
@prefontaine I think you're going to take point on this. Next steps: 
- [x] get greenlight from Chris / Lainie on general approach 
- [x] draft email copy w. links
- [x] make a google form. (so we can easily tabulate responses.) 
- [x] identify 10 / 15 people to send it to. (Ideally: people we were going to email anyway.) 
- [x] press send
- [x] share the results back w. stakeholders

cc @chrislarry33

**Comment by OpenMatt** [comment]
@prefontaine what do you think about us sending a mail to everyone currently on the StoryEngine site saying something like:

"Hey! your story is up. here it is [link]

Your story is a great example of why Mozilla is building a network of people like you and the others you see on the site. We working to launch the network next month. 
[one sentence on what the network launch is]

As a leader in this community, we wanted to ask your help: what do you think we should call this network? 
[a bit of context]

You can help us by taking 60 seconds to do this quick survey:
[link to google form]

Thanks!

**Comment by OpenMatt** [comment]
cc @ldecoursy

**Comment by OpenMatt** [comment]
The plan is scoped out here: https://public.etherpad-mozilla.org/p/networknameresearch
The deck is here: https://docs.google.com/presentation/d/15jWoJ5_DSkHlpk6R5j98niqBiAueg0ePqo4nAnjITxw/edit?ts=58910e10#slide=id.p
Mock up of site here for a bit of context: https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens

**Comment by ldecoursy** [comment]
A few quick things:

1) Not everyone will make it on the site at launch (think @xmatthewx said we'll start with 25-ish) so might want to tweak that language. 

2) How many people are on StoryEngine already? Just thinking if you blast out a survey to them, is that same kind of mix as what we scoped out in the plan (re varying degrees of involvement)?

**Comment by OpenMatt** [comment]
@ldecoursy 

* agree re language. updated. still hacky -- just trying to get the basic outline right. 
* 16 stories are published right now.

**Comment by ldecoursy** [comment]
@OpenMatt Can you share the google form when you get a chance?

**Comment by OpenMatt** [comment]
Draft email copy: https://public.etherpad-mozilla.org/p/stories
Draft google form: https://goo.gl/forms/89DIg9CScbxXgv4k1

@ldecoursy please feel free to edit it

**Comment by OpenMatt** [comment]
@ldecoursy: Draft google form: https://goo.gl/forms/89DIg9CScbxXgv4k1

Feel free to edit it.

**Comment by OpenMatt** [comment]
Next steps: get review / approval on email copy + form from:
- [x] @prefontaine 
- [ ] @xmatthewx 
- [x] @ldecoursy

**Comment by prefontaine** [comment]
I can't edit the form. But the change I have is to add the subtitles to the naming options that don't mention Mozilla. Important that people understand that will still be there. 

**Internet Health Network**
_Powered by Mozilla._

**Net Collective**
_Powered by you. Guarded by Mozilla._ 

(Less important: We may want to consider sharing a little mockup for each one.)

**Comment by OpenMatt** [comment]
Ok updated the form now.

**Comment by OpenMatt** [comment]
@prefontaine can you go ahead and email this to 10 - 15 members today, letting them know that the deadline to respond is Thursday? 

Also: @prefontaine can you share w. 2 - 3 contacts of your contacts not already in the network?

**Comment by OpenMatt** [comment]
Emailed Chris + Mark Surman to see if they have anyone they want to mail to as well.

**Comment by prefontaine** [comment]
@OpenMatt Yes

**Comment by prefontaine** [comment]
@OpenMatt This is done. Plus send out to some folks not yet in the network.

**Comment by prefontaine** [comment]
Re-opening because closed by mistake.

**Comment by prefontaine** [comment]
So far 10 responses via survey. One interview completed and two more booked for today.
