### ISSUE TITLE
Promote Hawaii report

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#76]

**Comment by prefontaine** [comment]
Published here: https://storyengine.io/insights/

1. Email for participants thanking them for their participation and welcoming feedback and continued engagement.

2. Email for staff thanking them for all their help and letting them know more to come.

3. Some external-facing content chunks for comms? Might they want to share more broadly, emphasizing the feedback loop, commitment to being a learning organization?

**Comment by OpenMatt** [comment]
@prefontaine : (1) and (2) are no-brainers for sure. @Lottarao might be able to help advise on en email to all staff. Should probably be framed as: "As we prepare to launch the network, here's a reminder of some of what we heard from members that is helping to inform the launch."

for (3), I wonder if a better investment of energy is: crafting an explicit plan w. MoFo comms (+ MoCo marketing, if they're helping to promote the Mozilla Network in various ways) for how our stories are going to tie into the larger social marketing plan for the network post launch. e.g., a drip campaign grouped by theme where one new story gets shared out per week? 

e.g., focus on the stories vs. the insights for external. that will drive a lot more awareness / traction...

**Comment by OpenMatt** [comment]
@prefontaine maybe we mark this done? We can include a link to it in our storytelling for e-180, biz dev, etc.

**Comment by prefontaine** [comment]
Yeah so this never really got leveraged properly because my time was hijacked by the network naming questions. But I do point to it a TON. Will check with Chris to see if he'd like a similar format for next AllHands -- or whenever.
