### ISSUE TITLE
Add people to the Mozilla Network site spreadsheet

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#78]
MLN Site-People spreadsheet: https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792

**Comment by OpenMatt** [comment]
@prefontaine is making good progress here

**Comment by OpenMatt** [comment]
@prefontaine anything else left to do on this one from our side?

**Comment by prefontaine** [comment]
A few more quotes to add as I process the open web fellows interviews. But I think they have enough to work with for now.

**Comment by prefontaine** [comment]
@OpenMatt @xmatthewx I'm going to close this now. I have quotes for all of the people I've processed. Will continue to add as I process, with focus on Open Web Fellows and Host Orgs. Also have shortened quotes on http://storyengine.io (these are same for folks who are in spreadsheet).

**Comment by OpenMatt** [comment]
yay!

**Comment by xmatthewx** [comment]
Thanks so much for all your work! I'm thrilled with how it's coming together.
