### ISSUE TITLE
Add "issues" page to StoryEngine.io

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#8]
Move this page to the StoryEngine site, and add it to the nav / frontpage so people can find it: https://openmatt.org/our-issues/

**Comment by prefontaine** [comment]
Hi Matt. I did that this morning. And added filter by type. I'll make it more obvious. http://storyengine.io/our-stories/

**Comment by OpenMatt** [comment]
Ok awesome! Can we call it http://storyengine.io/issues instead? I'll update in the tip form.
