### ISSUE TITLE
Make a how to page for: "how to produce an approved transcript" 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#80]
@prefontaine one question here: is Alecia already helping with this part? If so let me know, so I can work on it w. her / test w. her?

**Comment by prefontaine** [comment]
I'll ask her.

**Comment by prefontaine** [comment]
@ankuhl can you see this? We're wondering if you can work with @OpenMatt to help document the work you're doing — so others can join in.

**Comment by ankuhl** [comment]
@OpenMatt @prefontaine: Figuring this out as I go!  Finally made my way here:) I will def start taking notes on how I'm processing interviews. Let me know if there is anything I need to know to make sure I'm documenting the things you need, thanks!

**Comment by OpenMatt** [comment]
Awesome!

Let's start a google doc here:
https://docs.google.com/document/d/1jOHDKNiZgD-KYCmEIrNT90_bOSKQSBczef__z613gS0/edit

And we can add notes there together.

**Comment by prefontaine** [comment]
I added a bit with common mistakes, along with a table of examples.

**Comment by prefontaine** [comment]
@chrislarry33 Alecia and I worked on this and ready for review. https://docs.google.com/document/d/1jOHDKNiZgD-KYCmEIrNT90_bOSKQSBczef__z613gS0/edit?usp=sharing cc @OpenMatt

**Comment by OpenMatt** [comment]
I have some thoughts about formatting and stuff. I'll do that today.

**Comment by OpenMatt** [comment]
This is so awesome. Done!

**Comment by chrislarry33** [comment]
agreed!
