### ISSUE TITLE
Add meta-data back to post preview

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#81]
@prefontaine I made a change to the CSS to hide the post "categories" from the preview card. But now I'd like them to have them appear again.

Do you know to do that by any chance? I have zero CSS knowledge.

**Comment by prefontaine** [comment]
I'll take a look. Did you make the change to the main theme or the child
theme? I created the child theme for tweaks like this.

**Comment by OpenMatt** [comment]
I think the main theme. It was a while back.

**Comment by prefontaine** [comment]
A while back like before I did this last re-design?

**Comment by OpenMatt** [comment]
duplicate. marking closed.
