### ISSUE TITLE
Interview 3 - 5 people re: MLN naming options

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#82]
### How to do it: 
* book skype / phone interviews with 3 - 5 people 
* you can walk them through the questions in this form. Fill in the answers for them as they talk. https://mzl.la/naming_test
* the part we're especially interested in is: their freeform thoughts around *why* they rate these names the way they do. With quotes that we can pull from them to help boost our own understanding. They "1 - 5" reactions are not as important as their qualitative feedback. 
* submit their answers when done, so that we can gather them all into one spreadsheet. This will make it easier to track and co-ordinate. 
* the spreadsheet is here: https://mzl.la/responses

**Comment by OpenMatt** [comment]
### Next steps: assigning staff / scheduling chats 

* @chrislarry33: you said you'd be up for assigning a few staff to help with this. does this ticket give you what you need to do that? @ldecoursy can you help with that?
* @prefontaine do you have any interviews already scheduled this week that you could tack this onto?

**Comment by prefontaine** [comment]
@OpenMatt I may have one. I will set up others.

**Comment by prefontaine** [comment]
@OpenMatt Just coming back to this. I only have one potential interview this week. Shall I just pick other folks and set up interviews — or do you want to coordinate on who?

**Comment by arlissc** [comment]
@OpenMatt @prefontaine - do I suggest interviewees ? or is there a list that I pick from ? or am I assigned interviewees ?

**Comment by OpenMatt** [comment]
@arlissc you can go ahead and reach out to whatever members you like. 
email template to use is here: https://public.etherpad-mozilla.org/p/stories

**Comment by OpenMatt** [comment]
@prefontaine no need to co-ordinate -- just forge ahead w. whoever you
think's good, and update here in the ticket.

**Comment by arlissc** [comment]
@OpenMatt @prefontaine - have reached out to Science and Open Web fellows (they are on a workweek in SF) - will be doing interviews with them on Friday afternoon ET.  Have yet to confirm which ones however, will be doing 2 Science / 2 Open Web.

**Comment by arlissc** [comment]
by interview I mean completing the MLN naming_test form with their responses.

**Comment by arlissc** [comment]
Have completed naming_test with ...
Kirstie Whitaker (Fellow for Science 2016)
Etienne Maynier (Open Web Fellow 2016)
Steven Van Tuyl (new Study Group lead)

Upcoming interviews (Monday)
Eireann Leverett (Open Web Fellow 2016)

cc @OpenMatt @prefontaine

**Comment by chrislarry33** [comment]
Fantastic @arlissc Thanks! Would you be willing to interview Auerilla and get her to recommend a former OpenNews fellow as well?
