### ISSUE TITLE
Sync w. recognition program 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#91]
Christine + Rizwan chat. Next steps for recognition program in Q2. 
Implement: This time around: the person who nominates them has to interview.

**Comment by prefontaine** [comment]
Sent email to Rizwan. Did not see him in GitHub list.

**Comment by OpenMatt** [comment]
@prefontaine done?

**Comment by OpenMatt** [comment]
I'm going to mark as closed. will schedule a separate ticket to be more specific re: kicking off Staff Interview Recognition program.
