### ISSUE TITLE
Synch w. member outreach plans

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#92]
Ping Lainie. Get a clear sense of how we can best support that work.

**Comment by prefontaine** [comment]
@ldecoursy Do you want to set up a time to synch up? March 14-17? If so, you can pick length/day here:

https://calendly.com/christine-prefontaine/60-minute-call/
https://calendly.com/christine-prefontaine/45-minute-call/
https://calendly.com/christine-prefontaine/30-minute-call/
