### ISSUE TITLE
Start using StoryEngine resources in on-boarding

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#96]
@MandyRawls a while ago we talked about using StoryEngine in on-boarding. The site is at a point where I think it's ready to be incorporated. In a few ways:

1) Share the site in the on-boarding manual / process 
https://storyengine.io/

2) Point them at stories around specific issues. To help these geeky / technical "internet health" issues come to life for people who are new to them.

https://storyengine.io/category/stories/web-literacy/
https://storyengine.io/category/stories/privacy-security/
https://storyengine.io/category/stories/digital-inclusion/
https://storyengine.io/category/stories/open-innovation/
https://storyengine.io/category/stories/decentralization/

3) Invite new hires to interview a member of Mozilla's network
It's well-documented, fun and easy to do. And could be a great way to build empathy and understanding for what we do. This should be optional, of course, but we've done this w. a few staff already and it's gone really well. It's a great way to reach out to an actual human we serve and have a moment of human connection with them. 

Everything they need is here: 
https://storyengine.io/interview/

cc @maukland

**Comment by OpenMatt** [comment]
cc @prefontaine

**Comment by prefontaine** [comment]
@MandyRawls Please let me know if you have any questions re StoryEngine. Happy to help out.
