### ISSUE TITLE
Switch to new / better transcription service

### ISSUE THREAD

**Issue by prefontaine** [MozillaFoundation/Story-Engine#98]
Specialized freelancers who can learn about our field
People who can also take on editing
People who can handle multilingual

The idea here is to reduce editing time — we're just seeing way way too many ridiculous mistakes with Castingwords and they were not responsive to our feedback. 

I've already started doing research on this. Will pick up again week of March 13.

cc @ankuhl @openmatt

**Comment by OpenMatt** [comment]
next step:
* transcription communities / mechanical turk, etc.
* ideally: a higher quality person that we build a relationship with

**Comment by OpenMatt** [comment]
Good progress here. Will aim to have new folks in place by end of April. cc @prefontaine

**Comment by prefontaine** [comment]
@ankuhl Could you please drop any links/docs that I need to review in here?

**Comment by OpenMatt** [comment]
@ankuhl: ping

**Comment by ankuhl** [comment]
We've received just over 20 applications, to which I've narrowed it down to about 7.  Sending out a few emails to the first 3 or so applicants for them to sign NDAs and transcribe their first interview:)

https://drive.google.com/drive/folders/0B83QzxaFn4GqVXlSc3VMeE13Szg?usp=sharing

**Comment by ankuhl** [comment]
Sent out and received 2 NDAs/acceptance emails, one is currently working on transcription for an interview, and the other has already returned her first one!

**Comment by prefontaine** [comment]
Yay! Happy dance

**Comment by prefontaine** [comment]
This is DONE. On to maintenance mode.
